name: sync docker
on: push


env:
  USER: "${{ secrets.ALIYUNUSER }}"
  PASS: "${{ secrets.ALIYUNPASS}}"
  REGISTRY: "${{ secrets.ALIYUNREGISTRY }}"
  NAMESPACE: "${{ secrets.ALIYUNNAMESPACE }}"

jobs:
  pushtodocker:
    name: push
    runs-on: ubuntu-latest
    steps:
    - name: Read warehouse configuration
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: pull and push
      run: |
        cat image.txt
        docker login -u $USER -p $PASS $REGISTRY
        echo "==============begin"
        while  read -r line; do
        echo "in while"

        if [ ! -z $line ]

            eval $(echo $line | awk -F':' '{print "IMAGE="$1,"TAG="$2}')
              imageid=$(docker image ls |grep "${IMAGE}" |grep "${TAG}" | awk '{print $3}')
              dest="${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}"
              docker tag $imageid $dest
              docker push $dest  && echo "push successful" 
           

        done < image.txt 

        fi

        echo "==============end"