name: sync docker
on: push


env:
  USER: "${{ secrets.ALIYUNUSER }}"
  PASS: "${{ secrets.ALIYUNPASS}}"
  REGISTRY: "${{ secrets.ALIYUNREGISTRY }}"
  NAMESPACE: "${{ secrets.ALIYUNNAMESPACE }}"

jobs:
  pushtodocker:
    name: push
    runs-on: ubuntu-latest
    steps:
    - name: Read warehouse configuration
      uses: actions/checkout@v4
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
    - name: pull and push
      run: |
        docker login -u $USER -p $PASS $REGISTRY
        echo "==============begin"
        while IFS= read -r line; do
          if [ ! -z $line ];then
            awk -F':' '{print $1,$2}'| while IFS= read -r IMAGE TAG;do
             echo "push to ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}"
              docker tag $line ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}
              docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}  && echo "push successful" || echo "push failure"
            done
          else
             echo "There is no image to push"
          fi
        done < image.txt 
        echo "==============end"